apiVersion: apps/v1
kind: Deployment
label: 
  animal: tiger
metadata:
  name: rolling-deployment 
spec: 
  replicas: 2
  selector: 
    matchExpressions: 	
    - key: app
      operator: In
      values:
      - dhondhu
  strategy: 
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate  
  template:
    metadata:
      labels: 
        app: dhondhu  
      name: profile-pod  
    spec: 
      containers:
      - image: devopsinsiders/profile:v1
        name: akkicontainername
        ports: 
        - containerPort: 80
        resources: 
          limits:
            memory: "128Mi"
            cpu: "500"       